---
- name: Configure ETCD Server
  hosts: etcd_servers
  become: yes
  roles:
    - etcd_server

- name: Configure PostgreSQL Cluster with Patroni
  hosts: postgresql
  become: yes
  roles:
    - postgresql_cluster

- name: Install Docker and monitoring components
  hosts: docker_host
  become: yes
  roles:
    - docker_install