global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 'etcd01:9100'
          - 'pgsql01:9100'
          - 'pgsql02:9100'
          - 'docker01:9100'

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']