---
- name: Reload systemd and restart etcd
  become: yes
  ansible.builtin.systemd:
    name: etcd
    state: restarted
    enabled: yes
    sleep: 5
    daemon_reload: yes

- name: Start node_exporter
  become: yes
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes