---
- name: Add Docker GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg

- name: Add Docker repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: Install Docker Engine
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Ensure Python requests and docker modules are installed
  pip:
    name:
      - requests
      - docker
    executable: /usr/bin/pip3.8
  become: yes

- name: Add vagrant user to docker group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: yes

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

# --- Add node_exporter for Prometheus monitoring ---
- name: Create node_exporter group
  become: yes
  ansible.builtin.group:
    name: node_exporter
    state: present

- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    group: node_exporter
    shell: /sbin/nologin
    system: yes
    create_home: no
    state: present

- name: Download node_exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-1.7.0.linux-amd64.tar.gz"
    mode: '0644'

- name: Extract node_exporter
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: node_exporter
    group: node_exporter
    mode: '0755'
    creates: "/usr/local/bin/node_exporter"

- name: Create node_exporter systemd service file
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: Start node_exporter

- name: Enable and start node_exporter service
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes
    state: started
  become: yes

- name: Clean up downloaded node_exporter archive
  ansible.builtin.file:
    path: /tmp/node_exporter-1.7.0.linux-amd64.tar.gz
    state: absent
  become: yes

- name: Add ansible user to docker group
  ansible.builtin.user:
    name: ansible
    groups: docker
    append: yes
  become: yes

- name: Template docker-compose.yml with password
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /home/ansible/docker-compose.yml
    owner: ansible
    group: ansible
    mode: '0644'

- name: Template prometheus.yml to project root
  template:
    src: prometheus.yml.j2
    dest: "{{ playbook_dir }}/prometheus.yml"
    owner: ansible
    group: ansible
    mode: '0644'

- name: Copy prometheus.yml to target directory
  ansible.builtin.copy:
    src: prometheus.yml
    dest: /home/ansible/prometheus.yml
    owner: ansible
    group: ansible
    mode: '0644'

- name: Launch containers
  ansible.builtin.shell: docker compose -f /home/ansible/docker-compose.yml up -d
  args:
    chdir: /home/ansible
  become: yes

- name: Configure Grafana provisioning
  import_tasks: grafana_provisioning.yml