---
- name: Restart Patroni
  ansible.builtin.systemd:
    name: patroni
    state: restarted
    daemon_reload: yes

- name: Start node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes